Changes to create stack
concord-consortium/cloud-formation pull request #42
Opened 2021-01-12 18:32 UTC by knowuh

2021-01-12 22:36 UTC, kswenson commented on scripts/README.md
> +git will ginore `.yml` files in the `configs` and `stack-params` folders. Sample
```suggestion
git will ignore `.yml` files in the `configs` and `stack-params` folders. Sample
```

2021-01-12 22:36 UTC, kswenson commented on scripts/README.md
> +* `Template` -- the name of the CloudForamtion template yaml file to use
```suggestion
* `Template` -- the name of the CloudFormation template yaml file to use
```

2021-01-12 22:36 UTC, kswenson commented on scripts/README.md
> +reads a create-config.yml file and then duplicates
```suggestion
reads a `create-config.yml` file and then duplicates
```

2021-01-13 14:55 UTC, knowuh commented
@kswenson  — Thanks, you are always catching my typos! I appreciate that.

You have prompted me to install [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) for VSCode.

I will also try to remember to proof read my markdown files.  😄

2021-01-21 20:41 UTC, knowuh commented
@scytacki -- this PR has been rebased from #41

It could be reviewed after we convince ourselves that the template changes of #41 are not going to break deployments to production or staging learn.

2021-02-09 21:05 UTC, knowuh commented
@scytacki Do you think this work can be merged?  Some updates to the script and documentation.

2021-02-10 18:14 UTC, scytacki requested changes
I found one issue in the documentation. Otherwise it looks good.

2021-02-10 18:14 UTC, scytacki commented on README.md
> +	1. Select your primary AWS account credentials to copy stack parameters for the production Lara and Portal instances you are working on. `export AWS_PROFILE=concord-qa`
```suggestion
	1. Select your primary AWS account credentials to copy stack parameters for the production Lara and Portal instances you are working on. `export AWS_PROFILE=concord`
```

2021-02-10 18:20 UTC, scytacki commented
It is a little weird that this PR is showing changes that are already part of master. I'm going to merge master into this branch to remove those changes from the PR.

2021-02-10 20:36 UTC, scytacki approved these changes
Looks great.

2021-02-10 20:36 UTC, merged